### ISSUE TITLE
Some help needed please!

### ISSUE THREAD

**Issue by wammesjeroen** [juliuscc/heos-api#30]
Hey There!

thanks for this cool package! I was trying to use this at home and I succeeded to communicate with my HEOS devices. Now I want make a small Angular app and use node express to create APIs to control my devices. But I don't know how pass the response message (for example "now playing" back to the front end, via the API. You can log the responses from the HEOS device (callback function in "onAll" or "on" function), but you have to wait for the promises to be resolved:

app.get('/heos', function (req, res) {
test()
.then(function (data) {
res.send(data)
})
.catch(function (e) {
res.status(500, {
error: e
});
})
});

function test() {
const heos = require('heos-api')

return heos.discoverAndConnect().then(connection =>
connection
.onAll(collectData) //do something to collect return messages
.write('system', 'prettify_json_response', { enable: 'on' })
.write('system', 'heart_beat')
.write('player', 'get_now_playing_media', { pid: 1 })
)
}

Maybe you can help me a little bit?

thanks!

**Comment by juliuscc** [comment]
The problem is that the API is purely a stream of messages. When you send a 'volume_up' command to the device and get a 'volume_up, success' back it is obvious that your 'volume_up' was successful, but if you send many messages, there is no way to pair your messages with the responses perfectly.

I use a 'good enough' solution to translate the streams into promises that looks something like this:

``` javascript
const heos = require("heos");

const volumeUp = (connection) => (pid, step) =>
  new Promise((resolve, reject) => {
    connection
      .once(
        {
          commandGroup: "player",
          command: "volume_up",
        },
        (response) => resolve(response)
      )
      .write("player", "volume_up", { pid, step });
  });

heos
  .discoverAndConnect()
  .then((connection) => volumeUp(connection)(156, 10))
  .then(console.log);
```

`.once` is not a perfect solution cause the messages can come out of order, and then the wrong response will be paired with the wrong request. It is usually good enough for my use cases. Does this help you or was it something else?

**Comment by wammesjeroen** [comment]
Cool! Thanks a lot, this will help me indeed. I was also considering observables to do the trick, maybe I will experiment with them as well. 
Thanks again!

**Comment by juliuscc** [comment]
Observables can definitely be viable! That also sounds like a great idea. I think promises make sense for when you are trying to list players and such, but observables could make more sense for keeping a volume knob in an app up to date, or similar.
