### ISSUE TITLE
How to use players/get_players (if possible)

### ISSUE THREAD

**Issue by HawthornThistleberry** [juliuscc/heos-api#33]
There may be some underlying network issue here I can't figure out -- the same `discoverDevices` calls will fail ten times and then work five times with no changes in code -- so there may not be anything you can do for me. But there may be a code thing too.

I'm at the "hello world" stage of trying to make a webserver I can link via IFTTT webhooks to Alexa to give me Alexa commands to group and ungroup my three HEOS devices. I'd like to make it smart enough to keep working if my devices get different addresses, since MAC reservation is inconsistent in my network. Even when it works `discoverDevices` only gives me a list of IP addresses but not which is which, so I'm trying to pull the information in `players/get_players`. I am able to telnet to one of my devices manually and get this response no problem. But this code either gives me no devices found (most of the time), or `Heos response has wrong structure. Flushing buffer.` This is based on code you posted in another issue, though I've tried a dozen other tries, changing the sequence, using chaining instead of promises, etc. and had the same results throughout.

```javascript
const heos = require('heos-api');

const getPlayersInfo = (connection) =>
	new Promise((resolve, reject) => {
    connection
      .once(
        {
          commandGroup: "player",
          command: "get_players",
        },
        (response) => resolve(response)
      )
      .write("player", "get_players");
  });

heos
  .discoverAndConnect({port: '192.168.2.9'})
  .then((connection) => getPlayersInfo(connection))
  .then(console.log)
  .catch((err) => console.log('failed to get players info ' + err));
```
I'm really confused about how to get the HeosResponse at all, or why this isn't working. Is `players\get_players` *supposed* to work? Maybe I'm beating my head on a wall here when that command would never work this way?

**Comment by HawthornThistleberry** [comment]
To my shock, after literally hundreds of failed attempts, on a whim I just tried again and got the JSON response back just like that. So my code is actually all right, I think, and I just have to figure out why like 90-99% of communication attempts are failing. Which is probably no one's problem but mine! (Though if you have anything to suggest, I'm all ears.) Feel free to close.

**Comment by juliuscc** [comment]
If possible you could try to console.log more "raw" stuff from the devices. Whenever you get the message "Heos response has wrong structure. Flushing buffer." something very strange has happened, and this library doesn't have a good way of handling it.

Basically it means that the messages can not be parsed because they have a weird structure. Heos-api does its best by throwing out its buffer and trying to parse the next messages. The problem is if you are between messages, because then the buffer gets filled with half messages and you are back to square one.

What I would do is:
1. Clone this repo
2. Create a small hello world file in project root that looks like the one you sent, but replace `require('heos-api')` with `require('')`.
3. Add console.log statements in some places of the code
4. Compile the project by running `npm run build`
5. Run your test file by running something like `node temp.js`

I would recomend you placing a console.log statement right here https://github.com/juliuscc/heos-api/blob/a83496f75013b392d00e48977e9d409199eade24/src/listen/responseParser.ts#L92

**Comment by HawthornThistleberry** [comment]
The structure problem was apparently just a side effect of whatever is making 80-95% of my communications with my HEOS systems fail or time out. The other times it parses fine.

Still, if I can't figure *that* problem out, it's all moot. No service can be worth running if it fails that often (and takes so long to do it too).

**Comment by juliuscc** [comment]
Yes I agree that if you can't get the basic communication to work, nothing will work. It is a bit strange because messages are transmitted using TCP, so they shouldn't be received if they are incomplete. It has to be that your devices send bad data.

I suggest as a last check to print the raw packages that you receive. It might be that you get perfect messages but in another format for some reason.

**Comment by HawthornThistleberry** [comment]
I am finding evidence that the problems I'm having come from my Netgear Nighthawk router having bugs with multicast support, which I have also heard about having with my iDevices smart light switches. There are reports that problems like this have been around with Netgears for many years. *-sigh-*

The good news is, during those rare moments when the connectivity works, `heos-api` seems to work perfectly. I think I will have to shelve my programming efforts though until I can work out the idea of replacing my entire network.

Thanks for bearing with me (and for this software!).

**Comment by HawthornThistleberry** [comment]
Just to note... I replaced my network with Google Nest WiFi, and **every other trouble** I have had with multicast and connectivity is gone... but heos-api is still failing to discover devices 95+% of the time for no reason I can tell. If I give it a hardcoded IP address and do `heos.connect()` I can do `get_players` perfectly _once_, but everything else then just times out. I am baffled.

**Comment by juliuscc** [comment]
Are you having problems with both discover/connect and sending messages with an established connection? To test the messages sent over an established connection I recomend taking the actions mentioned above.

**Comment by juliuscc** [comment]
To test discovery you could run [heos.discoverDevices](https://github.com/juliuscc/heos-api#heosdiscoverdevicesoptions-ondiscover-ontimeout) for a couple of seconds. Log out the result and see what you get. If you need help understanding the result you can paste it here.

**Comment by HawthornThistleberry** [comment]
Discover commands either work perfectly (very rarely) or return nothing at all after a timeout; there's no packets to report, or they are exactly as they should be. That first post I made about an invalid format was a red herring. It's all about the discover commands simply timing out never finding anything at all. I can only connect via a direct connection to a hard-coded IP address. (Seems that connection doesn't last for very long though, so I have to reconnect the next time I want to send something to it.)

**Comment by juliuscc** [comment]
To me, this sounds like a network issue. Are you having other issues with your network, or does it work to use the official HEOS mobile app? If that doesn't work, there is nothing more that can be done, but if it does work, there might be some flaw in my implementation.

**Comment by HawthornThistleberry** [comment]
Wonder why the app has no such network problem, and now in my brand new Google Nest WiFi, everything else doesn't. But it's no one's problem but mine, and I can use a hardcoded IP address to direct connect to get around it.
