### ISSUE TITLE
Not discovering or connecting to any of my 3 denon devices

### ISSUE THREAD

**Issue by piejanssens** [juliuscc/heos-api#34]
- Denon Heos 1
- Denon AVR-X3400
- Denon AVR-X4500

Trying to connect using this script and it fails. 

```
const heos = require('heos-api')

heos.discoverAndConnect({ port: 8080, address: '192.168.1.199' }).then(console.log)

heos.discoverDevices({ timeout: 5000 }, console.log, () => { })

```

The CLI documentation says that the protocol used for connection is TELNET and discovery should happen using UPnP SSDP.

**Comment by piejanssens** [comment]
This works for discovery:
```
var SSDP = require('net-ssdp')
var discovery = new SSDP.Discovery()

discovery.on('search', (msg, rinfo, iface) => {
    var addr = `${rinfo.address}:${rinfo.port}`
    console.log(`M-SEARCH from ${rinfo.address} for "${msg.headers.st}"`, msg)
})

discovery.on('notify', (msg, rinfo, iface) => {
    console.log('NOTIFY', msg)
})

discovery.on('message', (msg, rinfo, iface) => {
    console.log('MESSAGE', msg)
})

discovery.listen((error) => {

    if (error) {
        throw error
    }

    console.log(discovery)

    function search() {
        console.log('Searching...')
        discovery.search({ st: 'ssdp:urn:schemas-denon-com:device:ACT-Denon:1' })
    }

    // interval = setInterval( search, 60000 )
    search()

})

process.on('SIGINT', () => {
    clearInterval(interval)
    discovery.close()
})

```

**Comment by juliuscc** [comment]
I used to use net-ssdp for heos-api but build the parts I used into heos-api so that the library becomes a 0 dependency library. By looking in https://github.com/juliuscc/heos-api/blob/master/src/connection/discover.ts I can see that I have hard coded some parts of the broadcast message. Also the host and port is hard coded.

I don't remember why that decision was made. Possibly because net-ssdp does that but I am not sure.

The library has worked for many others so there is no obvious fault, which makes this issue more complicated.

I have very little bandwidth to solve this issue, so if you want it solved you will have to do most of the heavy lifting yourself. As a final note, `/src/connection/discover.ts` will have everything that you search for. It is therefore not a lot of code to test.

You can download the repo and test parts by 1) running `npm run build`, 2) create a file in root that includes the library by doing `const heos = require('.')` and 3) running that file with `node <filename>`. Good luck!

**Comment by maszaa** [comment]
`heos.discoverAndConnect({ port: 8080, address: '192.168.1.199' }).then(console.log)`

port and address options for discover functions are for the ssdp to use a specific network interface in your computer. That's because at least with Windows the ssdp was binding to wrong network interface if Hyper-V was enabled and Docker was running. Usually one doesn't need to provide those so I would suggest you to try the discover without them first.

`heos.discoverDevices({ timeout: 5000 }, console.log, () => { })`

This will not connect to the devices but instead it will log all the IPs of the HEOS devices the discover finds. Change `console.log` to `heos.connect` to connect to devices. You may also use `heos.discoverAndConnect()`. Those return promises which resolve to a `HeosConnection` object.

If discovering still doesn't work, you may also connect to your HEOS devices without discovering. You just need to get the IP addresses of your HEOS devices in your local network and use `heos.connect`. You can get that information from the menu/setup of your HEOS device or from the HEOS app.

**Comment by piejanssens** [comment]
Thanks @maszaa 
I don't know why this time it's working, but just doing this it's showing my three device IP's:
```
const heos = require('heos-api')

heos.discoverDevices({ timeout: 5000 }, console.log, () => { })
```

**Comment by tommykjensen** [comment]
I get very inconsistent results from discovrDevices. Some days it works and somedays it won't work. Right now today it does not work.

**Comment by juliuscc** [comment]
Does it work if you try the same code as piejanssens presented above?

**Comment by juliuscc** [comment]
Are you sure that you are always on the same network as your heos device?

**Comment by tommykjensen** [comment]
Ahh I never tried to specify an adddress in the options. Then I do find the devices. The question though is how to find the correct interface to use because my pc has several network interfaces.

**Comment by juliuscc** [comment]
Maybe this is out of scope for heos-library. Your implementation could provide the user with a list of interfaces and ask the user to select one. And when the user has selected an interface your app (or whatever you call your implementation) can start searching for heos devices. You could also search using all your interfaces and then select whatever interface gives you results.

**Comment by maszaa** [comment]
> Ahh I never tried to specify an adddress in the options. Then I do find the devices. The question though is how to find the correct interface to use because my pc has several network interfaces.

Correct interface should be the one that has an IP from the DHCP server (i.e. your router) of your local network.

**Comment by tommykjensen** [comment]
I ended up using the SSDP library to find the network interface. But I will probably add a config file to override that.
