### ISSUE TITLE
Exception thrown during sign in

### ISSUE THREAD

**Issue by RobertMe** [juliuscc/heos-api#9]
Hi,

I'm using this library to communicate with my Denon AVR (which supports HEOS) but when using the ```system/sign_in``` method it throws an exception, specifically the ```Unexpected response received``` from ```useOneCallback``` (in ```eventHandler.js```, line 40).
Running Wireshark reveals that the receiver sends two replies to the sign_in command, being:
```
{
   "heos":{
      "command":"system/sign_in",
      "result":"success",
      "message":"command under process&un=<redacted>&pw=<redacted>"
   }
}
```
and
```
{
   "heos":{
      "command":"system/sign_in",
      "result":"success",
      "message":"signed_in&un=<redacted>"
   }
}
```
Because this command sends two responses (one being that it is being processed, and the second as success) it breaks the handling of messages into the callback.

As this exception is thrown from inside the message parsing of the library which is kicked of from the ```data``` event on the socket there is also no way to handle this exception, and it will thus stop the application (or at least it does in the case of Node-RED).

**Comment by juliuscc** [comment]
Firstly, thank you very much with the great feedback!

That is very much a problem. That is generally a problem with the library not being able to handle multiple answers, which has to be fixed.

Moreover, the ```"command under process...``` message is not at all specified in the heos docs.

To be honest I do not know the best way to solve this. The biggest problem is that the program should not panic just because it receives an unexpected message. The other problem is specifically to this sign_in message. Should the first message be ignored as that does not indicate anything relevant. It would be wierd if it would trigger the promise to resolve.

**Comment by RobertMe** [comment]
It seems like the ```system/sign_in``` command isn't the only command which shows this behavior. When doing a ```browse/search``` call it will also first reply with a ```comand under process```. So I guess that replies which have this element set on the message could/should just be ignored.

**Comment by juliuscc** [comment]
That would be a great temporary fix. ```command under process``` should really not resolve promises. It is really weird behaviour that it would trigger a ```success```.

I agree that we should ignore ```command under process``` at least if it is not an event. I am working on a commit

**Comment by juliuscc** [comment]
Commit 11a6ade276cfe60944f931434a0c2a2c46424292 should fix this

**Comment by juliuscc** [comment]
If you download version 2.1.1 you can try it out
